### ISSUE TITLE
Error: Error building site: TOCSS: failed to transform "css/site.sass" (text/x-sass): SCSS processing failed: file "stdin", line 2, col 1: File to import not found or unreadable: bulma/bulma.

### ISSUE THREAD

**Issue by akhromieiev** [orf/bare-hugo-theme#105]
Trying to use this template and have this error while deploy to netlify:

<img width="1197" alt="Screenshot 2020-09-05 at 00 32 24" src="https://user-images.githubusercontent.com/36918149/92286328-623e0100-ef0f-11ea-88d4-816dff3c1662.png">
Error: Error building site: TOCSS: failed to transform "css/site.sass" (text/x-sass): SCSS processing failed: file "stdin", line 2, col 1: File to import not found or unreadable: bulma/bulma.

Here is netlify config:

```
[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"```

**Comment by akhromieiev** [comment]
Installed postcss (and enabled it) and copied package.json. Now have this error:
<img width="1167" alt="Screenshot 2020-09-05 at 01 13 47" src="https://user-images.githubusercontent.com/36918149/92288301-302f9d80-ef15-11ea-82e6-f8255df9fe97.png">

**Comment by akhromieiev** [comment]
Also, the local build works fine: `hugo --gc --minify`

**Comment by akhromieiev** [comment]
@orf Hi! Could you help me, please?

**Comment by orf** [comment]
Don’t ping people like that. I’ll help when, or if, I have time to help. It’s also the weekend right now.

Your issue is that the git submodules for this theme are not being checked out by Netlify.

**Comment by orf** [comment]
Added a note to the readme about this 👍. I do appreciate the bug report, and I'm sorry for my tone in the previous comment, but something about highlighting me in your last comment struck me in the wrong way.

Nobody owes you any support, everyone is busy and in general it's good to wait at least a couple of days before notifying the owner of a repository in case they have missed your original notification.

Honestly, the error message seems pretty self explanatory: "Hugo cannot find bulma". Bulma is a git submodule. Searching for `netlify git submodule` on google [shows a fix as the second result](https://community.netlify.com/t/hugo-academic-cant-deploy-because-of-git-submodule/14846):

`git submodule update --force --recursive --init --remote && hugo ...`

**Comment by akhromieiev** [comment]
Hi, sorry for persistent asking (was trying to fix this all night and got nervous).

Will try to understand the issue.

Thank you and have a nice weekend!

**Comment by mozey** [comment]
Thanks for the nice theme!

Maybe I'm just ignorant but... **to avoid using git submodules (or netlify)**, the init can be done like this
```bash
# Ignore the theme
echo "www/themes/bare" >> path/to/your/.gitignore
# Clone the theme
cd www
git clone https://github.com/orf/bare-hugo-theme.git themes/bare
# Remove submodules and clone manually
rm themes/bare/.gitmodules
rmdir themes/bare/assets/css/bulma
rmdir themes/bare/assets/icons
echo "" >> themes/bare/.gitignore
echo "# Not using submodules" >> themes/bare/.gitignore
echo "/assets/css/bulma" >> themes/bare/.gitignore
echo "/assets/icons" >> themes/bare/.gitignore
git clone https://github.com/jgthms/bulma.git themes/bare/assets/css/bulma
git clone https://github.com/Templarian/MaterialDesign.git themes/bare/assets/icons
```

I also got **pipe failed error** when running `hugo serve`
```
Built in 197 ms
Watching for changes in .../www/{archetypes,content,data,layouts,package.json,static,themes}
Watching for config changes in .../www/config.toml
fatal error: pipe failed
```

The [solution](https://discourse.gohugo.io/t/too-many-files-only-on-non-root-user/35807) was to use
```
hugo server --poll 700ms
```
